# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/oscar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oscar)

$(call add-radio-file-sha1-checked,radio/abl.img,83466961e44a0e48d79803472d6d274f148928cb)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,5de8456289f7ddace534582151a29145822483d9)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,d7fe12a35e244b958eb941f98dd2ab132865b576)
$(call add-radio-file-sha1-checked,radio/devcfg.img,28a987d28e2a473ec9b6dc80ef43cbc7edb4fd88)
$(call add-radio-file-sha1-checked,radio/dsp.img,b1512787b130b7f9907aab41a05e471db8452675)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,1622dbd4869565ee981b4a50bce4b00ad9713ab4)
$(call add-radio-file-sha1-checked,radio/hyp.img,81e3e9193c96b259c802470f44add75bcdf0c296)
$(call add-radio-file-sha1-checked,radio/imagefv.img,dfe1a0695f4f3ad6328a3d67b1fd7266d04d6b92)
$(call add-radio-file-sha1-checked,radio/keymaster.img,be23cddb7cdd241b23b4966e8e8d13a5d8f8e609)
$(call add-radio-file-sha1-checked,radio/modem.img,477994b3d2ff48044633432343805c131fec5efc)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,f61c4ab7cf0f947e325859671f386c2e7c89bd08)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b757f44c9ccb5cf79feacfc419dd24d6cfdc5a18)
$(call add-radio-file-sha1-checked,radio/rpm.img,af90bcfddb38ec843fb21685de0a0c0e95196ab8)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,d69f91d400216cd42345c2b088c3938c78956cd2)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9f1ce08b4b717d81ee6d61f1c6a10a1ae2a30e71)
$(call add-radio-file-sha1-checked,radio/xbl.img,3eefaf9805933b86c23375b690b27a0e297fc2d7)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,205f900b5b410db8020ae7612466bfc31637bae2)

endif
