# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/oscar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oscar)

$(call add-radio-file-sha1-checked,radio/abl.img,343c2b2ebc60fe918ea26c74cff56703ae82d83c)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,37c50a239ed3f4fe5a348fe31017f66a746d0d2b)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,1cd63581780c947b2e8982d2c114aca8590d7ea2)
$(call add-radio-file-sha1-checked,radio/devcfg.img,a0b5eb2d57aa176bd4b9f2ef601d2bf3b6bccb50)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,90f086f3731fae87cd3dea22b6175faef667e4c2)
$(call add-radio-file-sha1-checked,radio/hyp.img,e98a12a179b4c3531eb09835bd5c4c3c91596cf3)
$(call add-radio-file-sha1-checked,radio/imagefv.img,37c8d90792338a25813d4ed538ee29034d73aa12)
$(call add-radio-file-sha1-checked,radio/keymaster.img,19b9c2d0c370638310560e581bd57efc66e507b3)
$(call add-radio-file-sha1-checked,radio/modem.img,f6f13540623fcea28c86050caf1d193abcf82003)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,5d61074056674862446713aeace57e7fde29b74a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0604b47777e002b05652e010daad270248939274)
$(call add-radio-file-sha1-checked,radio/rpm.img,f41830acb60ee76edf5b3dcc89c8c4c1e1bf9139)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,a9d558720ff4b436237eea4e8332d03d15f13a73)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,cb5845d9e86a99af9b3cbe1067bbe772529b714c)
$(call add-radio-file-sha1-checked,radio/xbl.img,e8e04d98c451ea14727b4a3dc40b96cbb84eebbd)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,0b5a27b3352a076781e67b66c25603c042f21ef3)

endif
