# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/oscar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),oscar)

$(call add-radio-file-sha1-checked,radio/abl.img,289e44a1d69d30692aac1735ee00a3411054dfae)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,2ba395463706f3959f423ed823829346d14582b5)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,aa3a379501a39bcc74e6afe4e952df2019365f6a)
$(call add-radio-file-sha1-checked,radio/devcfg.img,8088a53faf967de0c2af7522c2fa10fbcfdce081)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ff14fc74d19472a2d9523c15760c843e0550161e)
$(call add-radio-file-sha1-checked,radio/hyp.img,3394068a8652ae55612f90ef6518cc4cfbc28970)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f5dba307fe7e86f52607317a64cec30276806049)
$(call add-radio-file-sha1-checked,radio/keymaster.img,44ed955f07e76d40d477f26813e926a64ad2cd43)
$(call add-radio-file-sha1-checked,radio/modem.img,40a84bcc316406bd3217db8cf4c319c7aa3d1ed4)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,89682b339d5f7505f243e61fcd4cfa34b5aa665a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3481f66e3331f5ca537267ce709f25c8d0105a9b)
$(call add-radio-file-sha1-checked,radio/rpm.img,5963c1eee4d430017fb2dd8ea3272051a084729f)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,4402b941c28fb77cf68be62ec0cbde1b7ce28801)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,18fce8645df2cbde89da161e9edb8765c3fdfa3a)
$(call add-radio-file-sha1-checked,radio/xbl.img,d38bd98144cbc7d8cc9b7a13d508365616298e7b)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,ab691b9a4ee02aa21dffb3357aa416cd4da28030)

endif
